Repository RIT-MDRC/mdrc-pacbot, pull requests merged in 2024-09, with the labels that each got.

#57 set up robot properties
  core_pb/src/driving/network.rs
  core_pb/src/names.rs
  core_pb/src/robot_definition.rs
Labels: physical robot needed

#59 robot sends sensors back to server
  core_pb/src/driving/mod.rs
  core_pb/src/driving/network.rs
  core_pb/src/driving/peripherals.rs
  core_pb/src/lib.rs
  core_pb/src/localization.rs
  core_pb/src/messages/mod.rs
  core_pb/src/messages/server_status.rs
  pico_pb/src/i2c.rs
  server_pb/src/network.rs
  sim_pb/src/driving/mod.rs
  sim_pb/src/driving/peripherals.rs
  sim_pb/src/physics.rs
Labels: framework needed, high priority

#60 Make standard grid dropdown update simulator
  core_pb/src/messages/mod.rs
  gui_pb/src/drawing/game.rs
  gui_pb/src/drawing/tab.rs
  server_pb/src/main.rs
  server_pb/src/network.rs
  sim_pb/src/main.rs
  sim_pb/src/network.rs
  sim_pb/src/physics.rs
Labels: bug, high priority

#63 send cv location to robots for localization
  core_pb/src/driving/network.rs
  core_pb/src/driving/peripherals.rs
  core_pb/src/localization.rs
  core_pb/src/messages/mod.rs
  server_pb/src/main.rs
Labels: enhancement
